"""
Kalshi MLB Live Predictor
=========================
Fetches current MLB games from Kalshi API and generates betting recommendations
using the pre-trained MLB model (mlb_model.py).

Usage:
    python kalshi_mlb_predictor.py --kelly 0.5 --bankroll 100
"""

import argparse
import json
import os
import sys
import pickle
import warnings
from datetime import datetime, timezone
import numpy as np
import pandas as pd
import requests
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "mlb_historical_data")

# Kalshi API endpoints
KALSHI_API_BASE = "https://api.elections.kalshi.com/trade-api/v2"
KALSHI_MARKETS_ENDPOINT = f"{KALSHI_API_BASE}/markets"


# ═══════════════════════════════════════════════════════════════════════════
# ELO SYSTEM (from mlb_model.py)
# ═══════════════════════════════════════════════════════════════════════════

class EloSystem:
    """MLB Elo with staggered K-factor."""
    
    def __init__(self, home_advantage=24, mean_rating=1500, season_reversion=0.33):
        self.home_adv = home_advantage
        self.mean = mean_rating
        self.reversion = season_reversion
        self.ratings = {}
        self.last_season = None
    
    def _k_factor(self, rating):
        if rating < 1450:
            return 32
        elif rating <= 1550:
            return 24
        else:
            return 16
    
    def get_rating(self, team):
        return self.ratings.get(team, self.mean)
    
    def expected_score(self, home_elo, away_elo):
        diff = home_elo + self.home_adv - away_elo
        return 1.0 / (1.0 + 10 ** (-diff / 400.0))


# ═══════════════════════════════════════════════════════════════════════════
# LOAD TRAINED MODEL AND ELO RATINGS
# ═══════════════════════════════════════════════════════════════════════════

def load_model_and_elo(quiet=False):
    """Load the trained ensemble model and current Elo ratings."""
    
    # Try multiple sources for Elo ratings
    if not quiet:
        print("Loading Elo ratings...")
    
    # First try: elo_features.csv (generated by mlb_model.py)
    elo_path = os.path.join(DATA_DIR, "elo_features.csv")
    
    if os.path.exists(elo_path):
        if not quiet:
            print(f"  Loading from {elo_path}")
        elo_df = pd.read_csv(elo_path)
        
        # Get the most recent Elo ratings for each team
        latest_elo = {}
        for team in elo_df['home_team'].unique():
            home_games = elo_df[elo_df['home_team'] == team]
            away_games = elo_df[elo_df['away_team'] == team]
            
            if not home_games.empty:
                latest_home = home_games.iloc[-1]['home_elo']
                latest_elo[team] = latest_home
            elif not away_games.empty:
                latest_away = away_games.iloc[-1]['away_elo']
                latest_elo[team] = latest_away
    
    else:
        # Fallback: Try mlb_matchups_features_advanced.csv
        advanced_path = os.path.join(DATA_DIR, "mlb_matchups_features_advanced.csv")
        
        if os.path.exists(advanced_path):
            if not quiet:
                print(f"  elo_features.csv not found, loading from {advanced_path}")
            df = pd.read_csv(advanced_path)
            
            # Convert game_date to datetime and sort chronologically
            df['game_date'] = pd.to_datetime(df['game_date'])
            df = df.sort_values('game_date')
            
            # Get the most recent Elo for each team
            latest_elo = {}
            for team in df['home_team'].unique():
                home_games = df[df['home_team'] == team]
                away_games = df[df['away_team'] == team]
                
                if not home_games.empty and pd.notna(home_games.iloc[-1]['home_elo']):
                    latest_elo[team] = home_games.iloc[-1]['home_elo']
                elif not away_games.empty and pd.notna(away_games.iloc[-1]['away_elo']):
                    latest_elo[team] = away_games.iloc[-1]['away_elo']
        else:
            print(f"ERROR: Neither {elo_path} nor {advanced_path} found.")
            print("You need to either:")
            print("  1. Run mlb_model.py to generate elo_features.csv, OR")
            print("  2. Have mlb_matchups_features_advanced.csv with home_elo/away_elo columns")
            sys.exit(1)
    
    # Initialize Elo system with current ratings
    elo_system = EloSystem()
    elo_system.ratings = latest_elo
    
    if not quiet:
        print(f"  Loaded Elo ratings for {len(latest_elo)} teams")
        
        # Show sample ratings
        sorted_teams = sorted(latest_elo.items(), key=lambda x: x[1], reverse=True)
        print(f"  Top 3 teams: {', '.join([f'{t[0]}={t[1]:.0f}' for t in sorted_teams[:3]])}")
    
    # Try to load saved model if it exists
    model_path = os.path.join(BASE_DIR, "mlb_ensemble_model.pkl")
    
    if os.path.exists(model_path):
        if not quiet:
            print(f"Loading saved model from {model_path}...")
        with open(model_path, 'rb') as f:
            model_data = pickle.load(f)
        return elo_system, model_data
    else:
        if not quiet:
            print("No saved model found. Using Elo-only predictions.")
        return elo_system, None


# ═══════════════════════════════════════════════════════════════════════════
# FETCH KALSHI MARKETS
# ═══════════════════════════════════════════════════════════════════════════

def fetch_kalshi_mlb_markets(quiet=False):
    """Fetch current MLB game markets from Kalshi API."""
    
    if not quiet:
        print("\nFetching Kalshi MLB markets...")
    
    try:
        # Search for MLB markets with KXMLB prefix
        params = {
            "series_ticker": "KXMLB",
            "status": "open",
            "limit": 200
        }
        
        response = requests.get(KALSHI_MARKETS_ENDPOINT, params=params, timeout=10)
        response.raise_for_status()
        
        data = response.json()
        markets = data.get("markets", [])
        
        if not quiet:
            print(f"  Found {len(markets)} open MLB markets")
        
        # Filter out championship/futures markets
        game_markets = []
        championship_markets = []
        
        for market in markets:
            title = market.get("title", "")
            # Championship markets have "Championship" in title and close in 2028
            # Game markets have "beat" in title and close same day or next day
            if "Championship" in title or "win the 20" in title:
                championship_markets.append(market)
            elif "beat" in title.lower():
                game_markets.append(market)
        
        if not quiet:
            print(f"  - {len(championship_markets)} championship/futures markets (filtered out)")
            print(f"  - {len(game_markets)} game markets")
        
            # Debug: Print first few game market titles to see the format
            if game_markets:
                print(f"\n  Sample game market titles (first 3):")
                for i, market in enumerate(game_markets[:3], 1):
                    print(f"    {i}. {market.get('title', 'N/A')}")
                    print(f"       Ticker: {market.get('ticker', 'N/A')}")
        
        # Parse game markets to extract game information
        games = []
        
        for market in game_markets:
            ticker = market.get("ticker", "")
            title = market.get("title", "")
            subtitle = market.get("subtitle", "")
            
            # Try multiple parsing patterns for game markets
            home_team = None
            away_team = None
            
            # Pattern 1: "Will the [Team] beat the [Opponent]?"
            if "Will the " in title and " beat the " in title:
                try:
                    parts = title.replace("Will the ", "").split(" beat the ")
                    if len(parts) == 2:
                        home_team = parts[0].strip()
                        away_team = parts[1].strip().rstrip("?")
                except:
                    pass
            
            # Pattern 2: "Will [Team] beat the [Opponent]?"
            elif "Will " in title and " beat the " in title:
                try:
                    parts = title.replace("Will ", "").split(" beat the ")
                    if len(parts) == 2:
                        home_team = parts[0].strip()
                        away_team = parts[1].strip().rstrip("?")
                except:
                    pass
            
            # Pattern 3: "Will [Team] beat [Opponent]?" (no "the")
            elif "Will " in title and " beat " in title:
                try:
                    parts = title.replace("Will ", "").split(" beat ")
                    if len(parts) == 2:
                        home_team = parts[0].strip()
                        away_team = parts[1].strip().rstrip("?")
                except:
                    pass
            
            # Pattern 4: Check subtitle for team names
            elif subtitle:
                # Subtitle might have format like "LAD vs SD"
                if " vs " in subtitle or " @ " in subtitle:
                    separator = " vs " if " vs " in subtitle else " @ "
                    parts = subtitle.split(separator)
                    if len(parts) == 2:
                        if separator == " @ ":
                            away_team = parts[0].strip()
                            home_team = parts[1].strip()
                        else:
                            home_team = parts[0].strip()
                            away_team = parts[1].strip()
            
            if home_team and away_team:
                # Get market prices from yes/no ask prices (actual market prices)
                yes_ask = market.get("yes_ask", 50)
                no_ask = market.get("no_ask", 50)
                
                games.append({
                    "ticker": ticker,
                    "home_team": home_team,
                    "away_team": away_team,
                    "yes_price": yes_ask,
                    "no_price": no_ask,
                    "close_time": market.get("close_time", ""),
                    "title": title
                })
        
        if not quiet:
            print(f"  Parsed {len(games)} MLB games")
            
            if len(games) == 0 and len(game_markets) > 0:
                print("\n  WARNING: Found game markets but couldn't parse any games.")
                print("  This means the market title format might have changed.")
                print("  Please check the sample titles above and report the format.")
        
        return games
        
    except requests.exceptions.RequestException as e:
        if not quiet:
            print(f"ERROR fetching Kalshi markets: {e}")
        return []


# ═══════════════════════════════════════════════════════════════════════════
# TEAM NAME MAPPING
# ═══════════════════════════════════════════════════════════════════════════

# Map Kalshi team names to historical data team abbreviations
TEAM_NAME_MAP = {
    "Athletics": "OAK",
    "Angels": "LAA",
    "Astros": "HOU",
    "Blue Jays": "TOR",
    "Braves": "ATL",
    "Brewers": "MIL",
    "Cardinals": "STL",
    "Cubs": "CHC",
    "Diamondbacks": "ARI",
    "Dodgers": "LAD",
    "Giants": "SF",
    "Guardians": "CLE",
    "Mariners": "SEA",
    "Marlins": "MIA",
    "Mets": "NYM",
    "Nationals": "WSH",
    "Orioles": "BAL",
    "Padres": "SD",
    "Phillies": "PHI",
    "Pirates": "PIT",
    "Rangers": "TEX",
    "Rays": "TB",
    "Red Sox": "BOS",
    "Reds": "CIN",
    "Rockies": "COL",
    "Royals": "KC",
    "Tigers": "DET",
    "Twins": "MIN",
    "White Sox": "CHW",
    "Yankees": "NYY"
}

def map_team_name(kalshi_name):
    """Map Kalshi team name to abbreviation."""
    for key, abbr in TEAM_NAME_MAP.items():
        if key.lower() in kalshi_name.lower():
            return abbr
    return kalshi_name  # Return as-is if no mapping found


# ═══════════════════════════════════════════════════════════════════════════
# GENERATE PREDICTIONS
# ═══════════════════════════════════════════════════════════════════════════

def generate_predictions(games, elo_system, model_data=None, quiet=False):
    """Generate predictions for each game using Elo and/or trained model."""
    
    if not quiet:
        print("\nGenerating predictions...")
    
    predictions = []
    
    for game in games:
        home_abbr = map_team_name(game["home_team"])
        away_abbr = map_team_name(game["away_team"])
        
        # Get Elo ratings
        home_elo = elo_system.get_rating(home_abbr)
        away_elo = elo_system.get_rating(away_abbr)
        
        # Calculate Elo-based probability
        elo_prob = elo_system.expected_score(home_elo, away_elo)
        
        # For now, use Elo probability as the model probability
        # In future versions, this would use the full ensemble model
        model_prob = elo_prob
        
        # Calculate implied probabilities from market prices
        yes_implied = game["yes_price"] / 100.0
        no_implied = game["no_price"] / 100.0
        
        # Calculate edges
        home_edge = model_prob - yes_implied
        away_edge = (1 - model_prob) - no_implied
        
        predictions.append({
            "ticker": game["ticker"],
            "title": game["title"],
            "home_team": game["home_team"],
            "away_team": game["away_team"],
            "home_abbr": home_abbr,
            "away_abbr": away_abbr,
            "home_elo": round(home_elo, 1),
            "away_elo": round(away_elo, 1),
            "model_prob_home": round(model_prob * 100, 2),
            "yes_price": game["yes_price"],
            "no_price": game["no_price"],
            "yes_implied": round(yes_implied * 100, 2),
            "no_implied": round(no_implied * 100, 2),
            "home_edge": round(home_edge * 100, 2),
            "away_edge": round(away_edge * 100, 2),
            "close_time": game["close_time"]
        })
    
    return predictions


# ═══════════════════════════════════════════════════════════════════════════
# BETTING RECOMMENDATIONS
# ═══════════════════════════════════════════════════════════════════════════

def generate_betting_recommendations(predictions, bankroll, kelly_fraction, min_edge=5.0, quiet=False):
    """
    Generate betting recommendations based on predictions.
    
    Args:
        predictions: List of prediction dictionaries
        bankroll: Starting bankroll amount
        kelly_fraction: Fraction of Kelly criterion to use (0-1)
        min_edge: Minimum edge percentage to trigger a bet
        quiet: If True, suppress print statements
    
    Returns:
        List of betting recommendations sorted by edge
    """
    
    if not quiet:
        print(f"\nGenerating betting recommendations (min edge: {min_edge}%)...")
    
    bets = []
    
    for pred in predictions:
        home_edge = pred["home_edge"]
        away_edge = pred["away_edge"]
        
        # Only bet on the side with the larger edge, and only if > min_edge
        if home_edge > away_edge and home_edge > min_edge:
            # Bet on home team
            win_prob = pred["model_prob_home"] / 100.0
            market_price = pred["yes_price"] / 100.0
            
            # Kelly criterion: f = (p * (b + 1) - 1) / b
            # where b = (1 - market_price) / market_price (decimal odds - 1)
            b = (1 - market_price) / market_price
            kelly_fraction_optimal = (win_prob * (b + 1) - 1) / b
            
            # Apply Kelly fraction multiplier and ensure non-negative
            bet_fraction = max(0, kelly_fraction_optimal * kelly_fraction)
            bet_amount = min(bet_fraction * bankroll, bankroll * 0.20)  # Cap at 20% of bankroll
            
            if bet_amount > 1.0:  # Only recommend bets > $1
                potential_profit = bet_amount * b
                expected_value = bet_amount * home_edge / 100.0
                
                bets.append({
                    "bet_on": pred["home_team"],
                    "bet_abbr": pred["home_abbr"],
                    "opponent": pred["away_team"],
                    "opponent_abbr": pred["away_abbr"],
                    "home_away": "Home",
                    "elo_team": pred["home_elo"],
                    "elo_opponent": pred["away_elo"],
                    "model_prob": pred["model_prob_home"],
                    "market_price": pred["yes_price"],
                    "market_implied": pred["yes_implied"],
                    "edge": home_edge,
                    "bet_amount": round(bet_amount, 2),
                    "potential_profit": round(potential_profit, 2),
                    "expected_value": round(expected_value, 2),
                    "ticker": pred["ticker"],
                    "title": pred["title"],
                    "close_time": pred["close_time"]
                })
                
        elif away_edge > home_edge and away_edge > min_edge:
            # Bet on away team
            win_prob = (100 - pred["model_prob_home"]) / 100.0
            market_price = pred["no_price"] / 100.0
            
            b = (1 - market_price) / market_price
            kelly_fraction_optimal = (win_prob * (b + 1) - 1) / b
            
            bet_fraction = max(0, kelly_fraction_optimal * kelly_fraction)
            bet_amount = min(bet_fraction * bankroll, bankroll * 0.20)
            
            if bet_amount > 1.0:
                potential_profit = bet_amount * b
                expected_value = bet_amount * away_edge / 100.0
                
                bets.append({
                    "bet_on": pred["away_team"],
                    "bet_abbr": pred["away_abbr"],
                    "opponent": pred["home_team"],
                    "opponent_abbr": pred["home_abbr"],
                    "home_away": "Away",
                    "elo_team": pred["away_elo"],
                    "elo_opponent": pred["home_elo"],
                    "model_prob": round(100 - pred["model_prob_home"], 2),
                    "market_price": pred["no_price"],
                    "market_implied": pred["no_implied"],
                    "edge": away_edge,
                    "bet_amount": round(bet_amount, 2),
                    "potential_profit": round(potential_profit, 2),
                    "expected_value": round(expected_value, 2),
                    "ticker": pred["ticker"],
                    "title": pred["title"],
                    "close_time": pred["close_time"]
                })
    
    # Sort by edge (highest first)
    bets.sort(key=lambda x: x["edge"], reverse=True)
    
    if not quiet:
        print(f"  Found {len(bets)} betting opportunities")
    
    return bets


# ═══════════════════════════════════════════════════════════════════════════
# OUTPUT FORMATTING
# ═══════════════════════════════════════════════════════════════════════════

def format_close_time(iso_time):
    """Format ISO timestamp to readable format."""
    try:
        dt = datetime.fromisoformat(iso_time.replace('Z', '+00:00'))
        return dt.strftime("%I:%M %p ET")
    except:
        return "Unknown"


def print_recommendations(bets, bankroll, elo_system):
    """Print betting recommendations in formatted output."""
    
    print("\n" + "=" * 70)
    print("KALSHI MLB BETTING RECOMMENDATIONS")
    print("=" * 70)
    
    # Print Elo rankings
    print("\nTOP 10 TEAMS BY ELO RATING:")
    print("-" * 70)
    
    sorted_teams = sorted(elo_system.ratings.items(), key=lambda x: x[1], reverse=True)
    for i, (team, rating) in enumerate(sorted_teams[:10], 1):
        print(f"{i:2d}. {team:5s} | Rating: {rating:7.2f}")
    
    print("\n" + "=" * 70)
    
    if not bets:
        print("NO BETTING OPPORTUNITIES FOUND")
        print("\nThe model found no edges meeting minimum requirements.")
        print("This could mean:")
        print("  • No games available on Kalshi today")
        print("  • Market prices are too efficient")
        print("  • No significant edge detected")
        print("=" * 70)
        return
    
    print(f"FOUND {len(bets)} BETTING OPPORTUNITIES")
    print("=" * 70)
    
    total_wager = sum(bet["bet_amount"] for bet in bets)
    total_profit = sum(bet["potential_profit"] for bet in bets)
    total_ev = sum(bet["expected_value"] for bet in bets)
    
    for i, bet in enumerate(bets, 1):
        print(f"\nBET #{i}: {bet['bet_on']} vs {bet['opponent']}")
        print("-" * 70)
        
        home_away_icon = "🏠" if bet["home_away"] == "Home" else "✈️"
        print(f"BET ON: {bet['bet_on']} ({bet['bet_abbr']}) {home_away_icon}")
        print(f"OPPONENT: {bet['opponent']} ({bet['opponent_abbr']})")
        print(f"  Elo: {bet['elo_team']:.1f} vs {bet['elo_opponent']:.1f}")
        print(f"  Model probability: {bet['model_prob']:.2f}%")
        print(f"  Market price: {bet['market_price']:.0f}¢ (implies {bet['market_implied']:.2f}%)")
        print(f"  Edge: {bet['edge']:+.2f}%")
        print(f"  BET: ${bet['bet_amount']:.2f}")
        print(f"  Potential profit: ${bet['potential_profit']:.2f}")
        print(f"  Expected value: ${bet['expected_value']:.2f}")
        print(f"  Ticker: {bet['ticker']}")
        print(f"  Game time: {format_close_time(bet['close_time'])}")
    
    print("\n" + "=" * 70)
    print("PORTFOLIO SUMMARY")
    print("=" * 70)
    print(f"TOTAL WAGER: ${total_wager:.2f} ({total_wager/bankroll*100:.1f}% of bankroll)")
    print(f"POTENTIAL PROFIT: ${total_profit:.2f}")
    print(f"EXPECTED VALUE: ${total_ev:.2f}")
    print(f"BANKROLL REMAINING: ${bankroll - total_wager:.2f}")
    print("=" * 70)


# ═══════════════════════════════════════════════════════════════════════════
# JSON OUTPUT
# ═══════════════════════════════════════════════════════════════════════════

def get_json_output(predictions, bets, bankroll, elo_system):
    """Return results as a JSON-serializable dict."""
    sorted_teams = sorted(elo_system.ratings.items(), key=lambda x: x[1], reverse=True)
    rankings = [
        {"rank": i + 1, "team": team, "rating": round(rating, 2)}
        for i, (team, rating) in enumerate(sorted_teams[:10])
    ]
    
    total_wager = sum(bet["bet_amount"] for bet in bets)
    total_profit = sum(bet["potential_profit"] for bet in bets)
    total_ev = sum(bet["expected_value"] for bet in bets)
    
    return {
        "rankings": rankings,
        "bets": bets,
        "predictions": [
            {
                "home_team": p["home_team"],
                "away_team": p["away_team"],
                "home_abbr": p["home_abbr"],
                "away_abbr": p["away_abbr"],
                "home_elo": p["home_elo"],
                "away_elo": p["away_elo"],
                "model_prob_home": p["model_prob_home"],
                "yes_price": p["yes_price"],
                "no_price": p["no_price"],
                "yes_implied": p["yes_implied"],
                "no_implied": p["no_implied"],
                "home_edge": p["home_edge"],
                "away_edge": p["away_edge"],
                "ticker": p["ticker"],
                "close_time": p["close_time"],
                "title": p["title"]
            }
            for p in predictions
        ],
        "summary": {
            "totalBets": len(bets),
            "totalWager": round(total_wager, 2),
            "wagerPercent": round(total_wager / bankroll * 100, 1) if bankroll > 0 else 0,
            "totalProfit": round(total_profit, 2),
            "expectedValue": round(total_ev, 2),
            "bankrollRemaining": round(bankroll - total_wager, 2)
        }
    }


# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Kalshi MLB Live Predictor")
    parser.add_argument("--kelly", type=float, default=0.5,
                       help="Kelly fraction (default: 0.5)")
    parser.add_argument("--bankroll", type=float, default=100,
                       help="Starting bankroll in dollars (default: 100)")
    parser.add_argument("--min-edge", type=float, default=5.0,
                       help="Minimum edge percentage to bet (default: 5.0)")
    parser.add_argument("--json", action="store_true",
                       help="Output results as JSON instead of formatted text")
    
    args = parser.parse_args()
    
    if not args.json:
        print("=" * 70)
        print("KALSHI MLB LIVE PREDICTOR")
        print("=" * 70)
        print(f"Settings:")
        print(f"  Kelly Fraction: {args.kelly}")
        print(f"  Starting Bankroll: ${args.bankroll:.2f}")
        print(f"  Minimum Edge: {args.min_edge:.1f}%")
        print("=" * 70)
    
    # Load model and Elo ratings
    elo_system, model_data = load_model_and_elo(quiet=args.json)
    
    # Fetch Kalshi markets
    games = fetch_kalshi_mlb_markets(quiet=args.json)
    
    if not games:
        if not args.json:
            print("\n" + "=" * 70)
            print("NO MLB GAME MARKETS FOUND")
            print("=" * 70)
            print("\nIt's currently the MLB off-season (February).")
            print("Championship/futures markets are available, but no daily game markets.")
            print("\nMLB regular season typically:")
            print("  • Spring Training: Late February - March")
            print("  • Regular Season: Late March/Early April - Late September")
            print("  • Playoffs: October")
            print("  • World Series: Late October - Early November")
            print("\nCheck back when the season starts for daily game betting markets!")
            print("=" * 70)
        else:
            # JSON output for no games
            print(json.dumps({
                "rankings": [],
                "bets": [],
                "predictions": [],
                "summary": {
                    "totalBets": 0,
                    "totalWager": 0,
                    "wagerPercent": 0,
                    "totalProfit": 0,
                    "expectedValue": 0,
                    "bankrollRemaining": args.bankroll
                },
                "message": "No MLB game markets found. Season has not started yet."
            }, indent=2))
        return
    
    # Generate predictions
    predictions = generate_predictions(games, elo_system, model_data, quiet=args.json)
    
    # Generate betting recommendations
    bets = generate_betting_recommendations(
        predictions, 
        args.bankroll, 
        args.kelly,
        args.min_edge,
        quiet=args.json
    )
    
    # Output results
    if args.json:
        # JSON output for programmatic use (e.g., Flask app)
        result = get_json_output(predictions, bets, args.bankroll, elo_system)
        print(json.dumps(result, indent=2))
    else:
        # Human-readable formatted output
        print_recommendations(bets, args.bankroll, elo_system)


if __name__ == "__main__":
    main()